version: '3.3'

services:

    nginx:
        image: nginx
        container_name: nginx
        ports:
            - "7000:80"
            - "7443:443"
        volumes:
            - /var/run/docker.sock:/tmp/docker.sock:ro
            - ./html:/usr/share/nginx/html            
        restart: unless-stopped
